// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
 // ...
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzvI-xatU8MfgcfrurxPMh5MLaRh75wlk',
    appId: '1:426640441055:web:d795ea241ca2a29358336a',
    messagingSenderId: '426640441055',
    projectId: 'pass-angy-manager',
    authDomain: 'pass-angy-manager.firebaseapp.com',
    storageBucket: 'pass-angy-manager.appspot.com',
    measurementId: 'G-7GXJ6F4Y1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-NonX9-8sSxD4ZAxAAHlbjky5AQiQ0s',
    appId: '1:426640441055:android:4d500c6ed0d0737b58336a',
    messagingSenderId: '426640441055',
    projectId: 'pass-angy-manager',
    storageBucket: 'pass-angy-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC16FeUyJybNf0XuOryQttZN4p2t1gq8vY',
    appId: '1:426640441055:ios:89c1fac7482bef1258336a',
    messagingSenderId: '426640441055',
    projectId: 'pass-angy-manager',
    storageBucket: 'pass-angy-manager.appspot.com',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC16FeUyJybNf0XuOryQttZN4p2t1gq8vY',
    appId: '1:426640441055:ios:8ec361ccada25e7258336a',
    messagingSenderId: '426640441055',
    projectId: 'pass-angy-manager',
    storageBucket: 'pass-angy-manager.appspot.com',
    iosBundleId: 'com.example.passwordManager.RunnerTests',
  );

}
